language: java
jdk: oraclejdk8
before_install:
- 'sed -i "s/^\(version: \).*$/\1$main_version.$TRAVIS_BUILD_NUMBER/g" src/main/resources/plugin.yml'
after_success:
- cp build/libs/bloodmoon.jar ./bloodmoon-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITHUB_KEY@github.com/NyaaCat/bloodmoon --follow-tags
deploy:
- provider: releases
  skip_cleanup: true
  prerelease: true
  api_key:
    secure: "lRxskY8WMIDsXMHa6X/0pA1zbHgCXIQxkOvVS4cqr6xgtB187PELmjKtRQgDwiLKJvLaSYA3uh5GUSfPPdaoYstgAhcwApwE+a3O4I6FD3w7KJKmNWjxkLwJb2eXxEpcNDvw5yIzXLek9D1I9sEeaAm7BWo4U+uTzVoOG5v7p5r+1nG9A+MnFfqVaobB8IvNcCLMMy2uO/AhyfvV+lVP75LOr4HJBYvBn2mgOqZ8PW3lMHxNCMXLoq+BdYWjxEElGxx5tpn8pX0VbbC600AX6vkwOYqhFOK//JgOsN03ZI0XQ203lOtRG8BPxZkiecxZjEkcJdafE+GHsHnO8Imd52EtfXqa1jy7EaJtIZjev5wTHC7xb00pVwNt8Xk2uONDSh1LAk6eABzwnRHU+ldYdvX4hsvZhEOCq5+6FbIaMr7bSabUNzuiitIdMgWA6TNrbzlfXMF6Q3aWgpq87GKmU+E3WeuN4e1GJNnJUu9fmlPJh3fKzOTj9Kb9VffwXCdNuG4F+eX83WjWX1nypijy5qOS870YW6JNyHooa9fg5cJ/8OC2v0gOmQ4CsqNMMWXiFWVGADoxInuhTkyvr3dxmO2S0D+6zKC/GQ8MUwCoIHn0QUB0khePAXXPtoSFlwVOVZS5Fn/UTOTMlc0He9adh351Fe3zuU1cHAZL6fy0KmE="
  file: "./bloodmoon-$TRAVIS_BRANCH-v$main_version.$TRAVIS_BUILD_NUMBER.jar"
  on:
    tags: false
    all_branches: true
branches:
  except:
  - "/^*-v[0-9]/"
  - maven-repo
env:
  global:
  - main_version=1
  - secure: U5coyE3Ka38hwYXB3SmmF0PSHYrPsI3Bdv5B0MobgofN85LOjxcFgl+0rQN+GmO4M50QGucrqc6CN1k7IVIx55Y0SJuirR5ztheU4tlY7aTKmoGBEIMsgk0cXFZCfkMssydLblu47dST4W+hx2lBbvpt4REZoUpfUYnYwonjOAt9HCmc01iESJbnZlnkNhjyDeX3xPcdD/T/esfmzcvUrHgl+1w7jSSvabNXrgqZnbSElwXC6iMvk6RB6VvaItIwyDMsSMvTFq7GyB+ot7WQe5fOYeQzugvhD/vSTr+063nhRLyFWsfLQYpAV4Jg2Y0Zb62h8Fw1zqn1FBqYnqDyW5aV/Bd0FtlckdsiVAUGaTLf4yNBRmuGcDSgB8IGvjb08kP2kqazpWvuUFAJPVheG8JvdovkgGPFJTBMnZ/NyXEvc+MYMEQIrOZ9vbZTYUy/ol8OKCf3Xc/CxsgvBrs1WKHol4m3g9hRcrBgcsBAYPtG9O6D7f1UQ1uYt+Q8VbHa50I6LgfiDGt1CKgSSsKPDEaHGB+A3QGF4A7FmJcq8uywRi1S6mGe3icudokNhchSJQZJQUZCofeuMxKOf6SOliEp4iFeZJmkm6VhEJG9ucY59SjAb0tfz9wegE4nM3lmQXkn2MhaIyXyCnfRaLUwcjXq+zXa0GR666z+iJD/QPc=
